# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('slug', models.CharField(default='question', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='T_ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('user_uin', models.CharField(blank=True, max_length=12, null=True)),
                ('own_uin', models.CharField(blank=True, max_length=12, null=True)),
                ('own_name', models.CharField(blank=True, max_length=50, null=True)),
                ('own_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('service_combination', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('service_situation', models.CharField(blank=True, max_length=50, null=True)),
                ('label_one', models.CharField(blank=True, max_length=50, null=True)),
                ('label_two', models.CharField(blank=True, max_length=50, null=True)),
                ('label_Three', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('effect_level', models.CharField(blank=True, max_length=10, null=True)),
                ('functional_correlation', models.CharField(blank=True, max_length=50)),
                ('handel_person', models.CharField(blank=True, max_length=50, null=True)),
                ('team', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('queue_time', models.CharField(blank=True, max_length=10, null=True)),
                ('response_time', models.CharField(blank=True, max_length=10, null=True)),
                ('total_time', models.CharField(blank=True, max_length=10, null=True)),
                ('levelone_t', models.CharField(blank=True, max_length=10, null=True)),
                ('leveltwo_t', models.CharField(blank=True, max_length=10, null=True)),
                ('levelthree_t', models.CharField(blank=True, max_length=10, null=True)),
                ('levelFore_t', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_evaluation', models.CharField(blank=True, max_length=10, null=True)),
                ('ticket_ctime', models.DateField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=15, null=True)),
                ('job_number', models.CharField(blank=True, max_length=15, null=True)),
                ('ticket_status', models.CharField(blank=True, max_length=15, null=True)),
                ('tosb', models.CharField(blank=True, max_length=15, null=True)),
                ('is_solved', models.CharField(blank=True, max_length=15, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bootstrap.Question'),
        ),
    ]
